# enable UI plugin only when logging UI is enabled
{{- if .Values.logging.ui.enabled }}
apiVersion: observability.openshift.io/v1alpha1
kind: UIPlugin
metadata:
  name: logging
  labels:
      app: {{ template "logginghelm.name" . }}
      chart: {{ template "logginghelm.chart" . }}
      release: {{ .Release.Name }}
spec:
  type: Logging
  {{- end }}
