nameOverride: null

enabled: true

metrics:
  platformEnabled: false
  userWorkloadsEnabled: false

logging:
  enabled: false

tracing:
  enabled: false

analytics:
  incidentDetection:
    enabled: false

observabilityUI:
  enabled: false
  monitoring:
    enabled: false
  logging:
    enabled: false
  tracing:
    enabled: false
